eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      zone: http://localhost:8761/eureka/
      
microservice:
  payment-service:
    endpoints:
      endpoint:
        uri: http://PAYMENT-SERVICE/payment/getPayment/{price}
  shopping-service:
    endpoints:
      endpoint:
        uri: http://SHOPPING-SERVICE/client/payNow/{price}    
